<?php

namespace AppBundle\Repository;

/**
 * NoticesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticesRepository extends \Doctrine\ORM\EntityRepository
{
}
