<?php

namespace AppBundle\Repository;

/**
 * NoticesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOrderedByTime() {
        $em = $this->getEntityManager();
        $notices = $em->createQuery('SELECT n FROM AppBundle:Notices n WHERE n.date > CURRENT_TIMESTAMP()')->getResult();
        return $notices;
    }

}
